# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a78d308b65c93c461756163b5f313e595ec3b3e7270479aa4c21b730c8a2484c79df112380f41befa7e9e086ebc40ceab1efc4dcd3af9dac47139219a999ed9

test:
  secret_key_base: 301c2b7979ec36cb8c60f5bb192189b3544c80d6f6f4516ec75d9e6981d7e33d6988bc31fd6875bd061903907152d63e3c0564558dde24f9cf484fbe7b95bef2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
